JNG-4234 Add query count support for DAO / SDK / Rest
BlackBeltTechnology/judo-tatami-base pull request #54
Opened 2022-11-05 20:14 UTC by robertcsakany

JNG-4234 Add query count support for DAO / SDK / Rest

2022-11-06 22:43 UTC, noherczeg requested changes

2022-11-06 22:43 UTC, noherczeg commented on judo-tatami-asm2sdk/src/main/epsilon/templates/dao/DaoImpl.java.egl
> +                    .parameters(hu.blackbelt.judo.sdk.SdkUtil.asMap(effectiveParams))
What about offset?

2022-11-06 22:45 UTC, robertcsakany commented on judo-tatami-asm2sdk/src/main/epsilon/templates/dao/DaoImpl.java.egl
> +                    .parameters(hu.blackbelt.judo.sdk.SdkUtil.asMap(effectiveParams))
Its another Pull request!

2022-11-07 08:00 UTC, bencegelei approved these changes

2022-11-07 10:05 UTC, noherczeg approved these changes

2022-11-07 12:48 UTC, merged