JNG-4805 Performnance improvement
BlackBeltTechnology/judo-tatami-base pull request #93
Opened 2023-05-02 07:33 UTC by robertcsakany

JNG-4805 Performnance improvement

2023-05-03 08:46 UTC, gaborflorian approved these changes

2023-05-03 09:02 UTC, Madmat8 approved these changes

2023-05-03 09:12 UTC, noherczeg requested changes

2023-05-03 09:12 UTC, noherczeg commented on judo-tatami-asm2sdk/src/main/java/hu/blackbelt/judo/tatami/asm2sdk/Asm2SDKWork.java
> +                .useCache(workParameter.useCache)
Double cache call? WoW

2023-05-03 09:13 UTC, bencegelei requested changes

2023-05-03 09:13 UTC, bencegelei commented on judo-tatami-asm2sdk/src/main/java/hu/blackbelt/judo/tatami/asm2sdk/Asm2SDKWork.java
> +                .useCache(workParameter.useCache));
I'm pretty sure `useCache` will be set to `workParameter.useCache`'s value this way:D

2023-05-03 09:13 UTC, bencegelei commented on judo-tatami-psm2asm/src/main/java/hu/blackbelt/judo/tatami/psm2asm/Psm2Asm.java
> +            //psmModelContext.setUseCache(true);
Commented code?

2023-05-04 10:47 UTC, bencegelei approved these changes

2023-05-04 18:03 UTC, merged